INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('João-grande', 'Maguari Stork', 'Família Ciconiidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Cabeça-seca', 'Mycteria americana','Família Ciconiidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Gavião-de-rabo-branco','Geranoaetus albicaudatus','Família Accipitridae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Pernilongo-de-costas-brancas','Himantopus melanurus','Família Recurvirostridae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Pica-pau-branco','Melanerpes candidus','Família Picidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Noivinha-coroada','Xolmis coronatus','Família Tyrannidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Urubu-de-cabeça-vermelha','Cathartes aura','Família Cathartidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Veste-amarela','Xanthopsar flavus','Família Icteridae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Garibaldi','Chrysomus ruficapillus','Família Icteridae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Maria-preta-de-penacho','Knipolegus lophotes','Família Tyrannidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Ema', 'Rhea americana', 'Família Rheidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Calopsita', 'Nymphicus hollandicus', 'Família Cacatuidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Cacatua', 'Cacatuidae', 'Família Cacatuidae',NOW());
INSERT INTO ave (nome_Popular, nome_Cientifico, descricao,criado_em) VALUES ('Cacique', 'Icterus galbula', 'Família Icteridae',NOW());
